fix(eks-public): add ingress so the cluster can communicate with the ingress controller
Fix following error when deploying an exposed service in eks-public:

> Error: release artifact-caching-proxy failed, and has been uninstalled due to atomic being set: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://public-nginx-ingress-ingress-nginx-controller-admission.public-nginx-ingress.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded

Ref: https://github.com/kubernetes/ingress-nginx/issues/5401#issuecomment-1205318311